/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CopyConfigDialog: typeof import('./src/components/CopyConfigDialog.vue')['default']
    EditorialQuote: typeof import('./src/components/EditorialQuote.vue')['default']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    IpAllowlist: typeof import('./src/components/IpAllowlist.vue')['default']
    LiveLog: typeof import('./src/components/LiveLog.vue')['default']
    PositionTable: typeof import('./src/components/PositionTable.vue')['default']
    RechargeDialog: typeof import('./src/components/RechargeDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sparkline: typeof import('./src/components/Sparkline.vue')['default']
    StatusBar: typeof import('./src/components/StatusBar.vue')['default']
    TraderCard: typeof import('./src/components/TraderCard.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
